### ISSUE TITLE
Plans?

### ISSUE THREAD

**Issue by hildjj** [erdtman/cose-js#1]
I was just getting ready to start a full COSE implementation, and figured I'd check with you first.  I'm happy to collaborate if you like. I'll want tests, docs, coverage reporting, and pretty full spec coverage by the time we're done.  If that sounds like too much of a PITA, I'm also happy to just start my own.

**Comment by erdtman** [comment]
I would be happy to collaborate, better one good implementation then two poor once.

My initial intentions was to do a full implementation but mostly to validate the spec and test CWT stuff out.

**Comment by hildjj** [comment]
OK, expect a flurry of PRs from me, then.  I'll try to keep them separated by feature.  Your project, your rules, so let me know if you have strong feelings about coding standards, etc.
