### ISSUE TITLE
bluebird or anypromise?

### ISSUE THREAD

**Issue by hildjj** [erdtman/cose-js#3]
https://github.com/petkaantonov/bluebird/ is faster than q, and has some nice features.  Alternately, since this is a library that will likely be incorporated into other projects with existing promise libraries, we could use https://github.com/kevinbeaty/any-promise

**Comment by erdtman** [comment]
I have no strong opinion.
If you have worked with any-promise and not experiences any problems it looks like a good idea.

**Comment by erdtman** [comment]
I used q only because it was the first one I found

**Comment by hildjj** [comment]
I'll send a PR for any-promise.
