### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by letmaik** [erdtman/cose-js#42]
I'm unable to use this library currently due to the aes-ccm dependency. It got removed in https://github.com/erdtman/cose-js/pull/34. For reference, the aes-ccm library includes some binary and fails to load with `Error: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory`. A new release of core-js would be highly appreciated :)

**Comment by erdtman** [comment]
Sorry for the delay, just published a new version. Hope this enables you to use the library.

**Comment by letmaik** [comment]
Thanks!
