### ISSUE TITLE
incorrect function call ?

### ISSUE THREAD

**Issue by lovasoa** [erdtman/cose-js#44]
In https://github.com/erdtman/cose-js/blob/master/lib/encrypt.js#L309
the [createContext](https://github.com/erdtman/cose-js/blob/92a2b9a19bc84a584bc8c3f48c5f7d28e4055040/lib/encrypt.js#L148-L166) function is called without a value for the `alg` parameter.

`      keyLength[alg] * 8, // keyDataLength` is then evaluated to `NaN`.

Is that on purpose ?

I found this error while porting the code to typescript.

**Comment by erdtman** [comment]
That seems wrong

**Comment by iamgabrielsoft** [comment]
Something went wrong

**Comment by erdtman** [comment]
I had a deeper look and it looked like work in progress without tests so I removed that section to not confuse things. The section should likely look very much like the one above since it only supports one recipient as it stands today.
