### ISSUE TITLE
Best way to get the kid?

### ISSUE THREAD

**Issue by piotrblasiak** [erdtman/cose-js#50]
I have multiple keys, and I need to know the kid I should use before verifying the signature. What is the best way to do that?

**Comment by iamgabrielsoft** [comment]
You mean key, right?

**Comment by iamgabrielsoft** [comment]
I would attend to this issue

**Comment by Nxtmaster10** [comment]
@iamgabrielsoft I have the same issue. I need to get the KID from the message before verifying it. Like at https://dencode.com/string/base45 the Base45/Zlib/COSE/CBOR feature. The goal is to scan the vaccination certificate of a person. I am currently using the code from https://github.com/ehn-dcc-development/ehn-sign-verify-javascript-trivial and have read through the sites provided [here](https://github.com/eu-digital-green-certificates/dgc-overview/issues/43#issuecomment-899248004). Any suggestions?

**Comment by iamgabrielsoft** [comment]
I would look into this

**Comment by iamgabrielsoft** [comment]
That a good suggestion @Nxtmaster10 

This has to be a good suggestion for a method that needs to be implemented 🤔

**Comment by vitorpamplona** [comment]
@Nxtmaster10 @piotrblasiak 

You can use a CBOR lib to decode the payload first. 

You can see [here](https://github.com/Path-Check/dcc-sdk.js/blob/a58346098699e96e8fd0e2684b4cc36dbb90ab3e/lib/dcc.js#L139) how we are using a CBOR decoder to get the KID tag. Just remember that, for the DCC, you want to check the [protected and unprotected](https://github.com/Path-Check/dcc-sdk.js/blob/a58346098699e96e8fd0e2684b4cc36dbb90ab3e/lib/dcc.js#L201) parts of the payload.

**Comment by erdtman** [comment]
for now I would +1 on the comment from @vitorpamplona, in some glorious future where I have more time to work on this I could add a two step verification process where you would first read the signed/mac:ed object to get kid and other stuff and then do the cryptographic verification.
