### ISSUE TITLE
Modifying Code

### ISSUE THREAD

**Issue by iamgabrielsoft** [erdtman/cose-js#54]
**`I'm`** willing to modify the code to be easier to maintain!

**Comment by erdtman** [comment]
That sounds awesome, I have limited amount of time to spend on this library so any help is appreciated. If it works out well I would be happy to make you contributor

**Comment by iamgabrielsoft** [comment]
That sounds good, currently working on the codes👌

**Comment by iamgabrielsoft** [comment]
Merge the encrypt file and Common file
