### ISSUE TITLE
Issues signing large payloads

### ISSUE THREAD

**Issue by palmenhq** [erdtman/cose-js#55]
PR https://github.com/erdtman/cose-js/pull/53 solved issues signing large payloads (redirecting there for an in-depth description). However i believe there must've been a merge conflict because #48 removes this feature (`sign.js` [L106](https://github.com/erdtman/cose-js/pull/48/files#diff-02346278010f5099e4be2cae18e3a443e44892be47996d75abf55602e0349b8bL106) and [L125](https://github.com/erdtman/cose-js/pull/48/files#diff-02346278010f5099e4be2cae18e3a443e44892be47996d75abf55602e0349b8bL125)). Additionally it [alters the sign performance test](https://github.com/erdtman/cose-js/pull/48/commits/20f654369f1dd696d1b2b3794e483494145518b5) to test only ~16kb payloads (which is the highwatermark in node-cbor).

It would be great to get this feature back. I'm happy to put up a pr for this later, but i figured i would highlight this until then in case someone else would face the same issue 👍

cheers!

**Comment by erdtman** [comment]
My bad, I was not careful when merging, it should be fixed now. Will release a new version later today

**Comment by erdtman** [comment]
should be fixed now
