### ISSUE TITLE
No "protected" field in example

### ISSUE THREAD

**Issue by jumpjack** [erdtman/cose-js#57]
https://github.com/erdtman/cose-js/blob/6bade143df9f9a2351c84fa94a6da11e3656258f/test/sign1-tests.js#L14

The "protected" field mentioned in this line is not present in the [file](https://github.com/cose-wg/Examples/blob/3221310e2cf50ad13213daa7ca278209a8bc85fd/sign1-tests/sign-pass-01.json)   loaded by jsonfile.readFileSync('test/Examples/sign1-tests/sign-pass-01.json") (but it is present in pass-02 and pass-03).

**Comment by erdtman** [comment]
Thanks, I just removed it
