### ISSUE TITLE
cbor "^7.0.6" fails to compile for Web / resolve node-inspect-extracted

### ISSUE THREAD

**Issue by aheissenberger** [erdtman/cose-js#59]
## Error
```
./node_modules/XXXXXXX/node_modules/cbor/lib/utils.js
Module not found: Can't resolve 'node-inspect-extracted' in '/path-on-disk/project-name/node_modules/XXXXXXX/node_modules/cbor/lib'
```

The Problem does not exist with `cose-js` version `0.6.0` as it requires `cbor` version `^3.0.0`

## Solution
The problem could be fixed by upgrading the current dependency for `cbor` from `^7.0.6` to `^8.1.0`

## QuickFix / Yarn 1

**package.json**
```json
"resolutions": {
    "cose-js/**/cbor": "^8.1.0"
},
```

**Comment by erdtman** [comment]
Just published a new version with the cbor version bumped to 8.1.0
