### ISSUE TITLE
Problem with minified Code

### ISSUE THREAD

**Issue by dfuchs2512** [erdtman/cose-js#60]
Hello, 

I use the following syntax in a Meteor/React APP and have problems just in production when the code is minified. In Development this part of code works perfect.

const verified = await cose.sign.verify(data, verifier) 

Problem is that in the minified version I get a "Signature missmatch" Error when the function verify is called. As I said in Development all works fine.

Maybe you have some hint what could cause this problem.

Thx Daniel

**Comment by erdtman** [comment]
sounds very strange, could you provide me with some example code to reproduce with?
