### ISSUE TITLE
How can i add x5chain in unprotected headers?

### ISSUE THREAD

**Issue by madhugoundla-oneproof** [erdtman/cose-js#67]
How to add x5chain to unprotected headers? 

    const headers = {
        p: { alg: 'ES256' },
        u: { kid: '11',
        crit: ["DER format of X509 cert"]
    }
    };

Adding x5chain doesn't work.

    const headers = {
        p: { alg: 'ES256' },
        u: { kid: '11',
        x5chain: ["DER format of X509 cert"]
    }
    };

**Comment by astanciu** [comment]
Also have this question. Is this library still maintained?

**Comment by madhugoundla-oneproof** [comment]
This worked for me.       
       
        const cert = '30820260....Der encoded cert';
        const certBuffer = Buffer.from(cert, 'hex');

        const headers = {
            p: { alg: 'ES256' },
            u: { x5chain: certBuffer }
          };
          
          you can add in unprotected or protected headers.
          
        Not sure about the library, but everything works.

**Comment by madhugoundla-oneproof** [comment]
You are correct, i have forked this repo and made changes as needed.

https://github.com/oneproof-inc/cose-js/tree/master

**Comment by astanciu** [comment]
Very nice! But fyi, think you need to update the header types too

**Comment by erdtman** [comment]
To be hones I have not put in any time working on this recently, and that is likely to stay that way for at least a few more months.

I would be happy to merge a pull request if you have working code @madhugoundla-oneproof

**Comment by madhugoundla-oneproof** [comment]
@erdtman i do have working code, how can i create pull request?

**Comment by erdtman** [comment]
Fork this repo and update the code accordingly, and point me to the repo and I can do the work of pulling in the code and publish  new version

**Comment by madhugoundla-oneproof** [comment]
@erdtman done https://github.com/madhugoundla-oneproof/cose-js

**Comment by erdtman** [comment]
merged and released
